"use client";

import { useEffect, useState, useCallback } from "react";
import { useRouter } from "next/navigation";
import Fuse from "fuse.js";
import { AnimatePresence, motion } from "framer-motion";
import { Search as SearchIcon, Command as CommandIcon, X } from "lucide-react";

type SearchItem = {
  title: string;
  slug: string;
  content: string;
};

export default function SearchPage() {
  const [index, setIndex] = useState<SearchItem[]>([]);
  const [query, setQuery] = useState("");
  const [results, setResults] = useState<SearchItem[]>([]);
  const [isOpen, setIsOpen] = useState(false);
  const router = useRouter();

  // Load search index JSON generated by your script
  useEffect(() => {
    fetch("/search-index.json")
      .then((res) => res.json())
      .then((data: SearchItem[]) => setIndex(data))
      .catch((err) => console.error("Failed to load search index", err));
  }, []);

  // Create Fuse instance when index changes
  const [fuse, setFuse] = useState<Fuse<SearchItem> | null>(null);

  useEffect(() => {
    if (!index.length) return;

    const f = new Fuse(index, {
      keys: ["title", "content"],
      threshold: 0.35, // fuzziness (lower = stricter)
      ignoreLocation: true,
    });

    setFuse(f);
  }, [index]);

  // Handle CMD/CTRL + K to open palette
  useEffect(() => {
    const onKeyDown = (e: KeyboardEvent) => {
      const isMac = navigator.platform.toLowerCase().includes("mac");
      const cmdOrCtrl = isMac ? e.metaKey : e.ctrlKey;

      if (cmdOrCtrl && e.key.toLowerCase() === "k") {
        e.preventDefault();
        setIsOpen((prev) => !prev);
      }
    };

    window.addEventListener("keydown", onKeyDown);
    return () => window.removeEventListener("keydown", onKeyDown);
  }, []);

  // Run search whenever query changes
  useEffect(() => {
    if (!fuse || !query.trim()) {
      setResults([]);
      return;
    }

    const fuseResults = fuse.search(query.trim());
    setResults(fuseResults.map((r) => r.item));
  }, [query, fuse]);

  const close = useCallback(() => {
    setIsOpen(false);
    setQuery("");
    setResults([]);
  }, []);

  const handleSelect = useCallback(
    (item: SearchItem) => {
      close();
      router.push(item.slug);
    },
    [close, router]
  );

  // Basic highlight: wrap query in <mark>
  const highlight = (text: string | undefined | null, q: string) => {
    if (!text || typeof text !== "string") return text || "";
  
    if (!q.trim()) return text;
  
    const escaped = q.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
    const regex = new RegExp(`(${escaped})`, "ig");
    const parts = text.split(regex);
  
    return parts.map((part, i) =>
      regex.test(part) ? (
        <mark key={i} className="bg-yellow-200 rounded px-0.5">
          {part}
        </mark>
      ) : (
        <span key={i}>{part}</span>
      )
    );
  };
  

  return (
    <div className="min-h-screen bg-gray-50 px-4 py-10">
      <div className="max-w-2xl mx-auto">
        {/* Header + inline search bar as backup */}
        <div className="flex items-center justify-between mb-6">
          <h1 className="text-2xl font-semibold tracking-tight">Search</h1>
          <button
            onClick={() => setIsOpen(true)}
            className="inline-flex items-center gap-2 rounded-full border px-3 py-1 text-sm text-gray-600 hover:bg-gray-100"
          >
            <CommandIcon className="w-4 h-4" />
            <span className="hidden sm:inline">
              Open command palette <span className="text-xs text-gray-400">(⌘K / Ctrl+K)</span>
            </span>
            <span className="sm:hidden">⌘K</span>
          </button>
        </div>

        <div className="relative mb-6">
          <SearchIcon className="absolute left-3 top-3 w-5 h-5 text-gray-400" />
          <input
            className="w-full pl-10 pr-4 py-3 rounded-2xl border border-gray-300 bg-white focus:outline-none focus:ring-2 focus:ring-black"
            placeholder="Search across pages…"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
          />
        </div>

        <div className="space-y-4">
          {query.trim() && results.length > 0 && (
            <>
              {results.map((item) => (
                <button
                  key={item.slug}
                  onClick={() => handleSelect(item)}
                  className="w-full text-left p-4 rounded-2xl bg-white shadow-sm hover:shadow-md transition flex flex-col gap-1"
                >
                  <div className="text-sm font-semibold">
                    {highlight(item.title, query)}
                  </div>
                  <div className="text-xs text-gray-600 line-clamp-2">
                    {highlight(item.content, query)}
                  </div>
                </button>
              ))}
            </>
          )}

          {query.trim() && results.length === 0 && (
            <p className="text-gray-500 text-sm">No results found.</p>
          )}

          {!query.trim() && (
            <p className="text-gray-400 text-sm">
              Type above or press <kbd className="px-1 py-0.5 rounded border text-xs">⌘K</kbd> /{" "}
              <kbd className="px-1 py-0.5 rounded border text-xs">Ctrl+K</kbd> to open the palette.
            </p>
          )}
        </div>
      </div>

      {/* Command palette modal */}
      <AnimatePresence>
        {isOpen && (
          <motion.div
            className="fixed inset-0 z-50 flex items-start justify-center bg-black/40 px-4 pt-24"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={close}
          >
            <motion.div
              className="w-full max-w-xl rounded-2xl bg-white shadow-xl border border-gray-200 overflow-hidden"
              initial={{ y: 20, opacity: 0 }}
              animate={{ y: 0, opacity: 1 }}
              exit={{ y: 20, opacity: 0 }}
              transition={{ type: "spring", stiffness: 260, damping: 24 }}
              onClick={(e) => e.stopPropagation()}
            >
              <div className="flex items-center border-b px-4 py-2 gap-2">
                <SearchIcon className="w-4 h-4 text-gray-400" />
                <input
                  autoFocus
                  className="flex-1 bg-transparent outline-none text-sm py-2"
                  placeholder="Search…"
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                />
                <button
                  onClick={close}
                  className="text-gray-400 hover:text-gray-600 p-1 rounded-full"
                  aria-label="Close"
                >
                  <X className="w-4 h-4" />
                </button>
              </div>

              <div className="max-h-80 overflow-y-auto">
                {query.trim() && results.length === 0 && (
                  <div className="px-4 py-6 text-center text-sm text-gray-500">
                    No results found.
                  </div>
                )}

                {!query.trim() && (
                  <div className="px-4 py-6 text-center text-xs text-gray-400">
                    Start typing to search. Use ↑ ↓ to move, Enter to open.
                  </div>
                )}

                {results.map((item) => (
                  <button
                    key={item.slug}
                    onClick={() => handleSelect(item)}
                    className="w-full text-left px-4 py-3 hover:bg-gray-50 flex flex-col gap-1"
                  >
                    <span className="text-sm font-medium">
                      {highlight(item.title, query)}
                    </span>
                    <span className="text-xs text-gray-600 line-clamp-2">
                      {highlight(item.content, query)}
                    </span>
                  </button>
                ))}
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
